### ISSUE TITLE
Filebeat (5.6): index created, but no documents

### ISSUE THREAD

**Issue by pardahlman** [elastic/stack-docker#12]
Thanks for a great way to getting started with the entire Elastic stack 👍 

I've previously used the now-depricated "library" docker images ([`library/elastic`](https://hub.docker.com/_/elasticsearch/) etc). The transition to these images has been close to friction-free, except for the fact that logs from Filebeat are not added to the Elastic index.

I'm running latest version of docker on Windows

```
> docker --version
Docker version 17.09.0-ce, build afdb6d4
```

**Steps to reproduce**

1. Checkout the branch `5.6.` and add a volume to `filebeat` so that `/mnt/log` contains some log files. I had to adjust the JVM heap size for the Elasticsearch container by adding the following environment variable `'ES_JAVA_OPTS=-Xms512m -Xmx512m'`
2. Run `docker-compose up` and wait for the containers to start up
3. Load list of indexes in Elasticsearch `http://localhost:9200/_cat/indices?v`

**Result**

I see a Filebeat index (`filebeat-2017.10.06`), but it does not contain any documents.

Looking at the log from the Filebeat container, I see the following (some log entries removed for readability)

```
INFO Harvester started for file: /mnt/log/my_log_file.log
ERR Connecting error publishing events (retrying): Get http://elasticsearch:9200: dial tcp 172.18.0.2:9200: getsockopt: connection refused
INFO Connected to Elasticsearch version 5.6.2
INFO Non-zero metrics in the last 30s: libbeat.es.call_count.PublishEvents=602 libbeat.es.publish.read_bytes=287614 libbeat.es.publish.write_bytes=19860998 libbeat.es.published_and_acked_events=29991 libbeat.publisher.published_events=28655 publish.events=28672 registrar.states.current=31 registrar.states.update=28672 registrar.writes=14
```

I'm not familiar with the inner workings of Filebeat, but if I read the logs right it looks like it successfully connected to elastic search (after a few retries) and published log entries to it. Further more I kind of ruled out authentication or connectivity problems, as the Filebeat index is created in Elasticsearch.

Do you have any idea what the problem might be or if I've missed something? Any help would be greatly appreciated!

**Comment by jarpy** [comment]
Hi, @pardahlman.

I suspect this is going to be something specific to Docker for Windows. I use a Windows desktop myself, so I'll have look around and let you know what I find. (Though it's Friday night here, so I must beg a little patience :) ).

**Comment by pardahlman** [comment]
Hello @jarpy - thanks for a quick reply. I was just going to say that I tried the `master` branch (version 6.0.0-beta2) and everything works fine.

**Comment by jarpy** [comment]
I must have fixed something... I wish I knew what!

Also, that reminds me to update the master branch to 6.0.0-rc1. Thanks.

**Comment by pardahlman** [comment]
I know that feeling 😉 . Anyways looking forward hearing what you find related to this issue. I'll pause the migration, as we can't run beta or rc releases atm. Thanks!

**Comment by jarpy** [comment]
Bind mounted volumes are completely broken on my Windows system right now, so I can't test this properly. Very frustrating...

However, I looked at the differences between the 5.x and 6.x images. The 5.x image [defaults to only ingesting files that are named `*.log`](https://github.com/elastic/beats-docker/blob/5.6/build/filebeat/config/filebeat.yml#L4). Is it maybe just that your files are not named liked this?

The 6.x image uses a [more sophisticated configuration](https://github.com/elastic/beats-docker/blob/6.x/build/filebeat/config/filebeat.yml#L3), due to the introduction of Filebeat Modules.

**Comment by pardahlman** [comment]
Top of the morning ☕️ ,

Thanks for looking into this - much appreciated. My log files named `*.log`, so that's not the problem. Actually, I'm starting to think that the problem lays in the Elasticsearch image, because: if I use `library/elasticsearch:5` instead of `docker.elastic.co/elasticsearch/elasticsearch:5.6.2`, the log files are index.

**Comment by jarpy** [comment]
And good afternoon to you. 🍻 

Interesting... thanks for the details.

I couldn't replicate the problem on a Linux host, so I really need to get Docker for Windows working.

**Comment by jarpy** [comment]
OK. I now have another Windows 10 licence and a working Docker for Windows. Phew.

I still couldn't reproduce this _exact_ failure mode, but I did get various funky behaviours. All my problems seemed to stem from not having enough memory in the Docker Linux VM. With the default heap size, I had to give the VM 5GB of RAM to get the entire stack working correctly. Even though you set your Elasticsearch heap size lower, I think your VM may still be running out of RAM.

I'm going to:

- Set the heap size for Elasticsearch to 1GB in `docker-compose.yml`
- Document in the README the required RAM allocation for the VM (see #13)

If you have enough RAM, please try setting your Docker VM to something large (5+ GB) and let me know if your problem goes away.
