### ISSUE TITLE
linux spec capabilities: Unknown capability to add: "CAP_AUDIT_READ"

### ISSUE THREAD

**Issue by amosbird** [elastic/stack-docker#14]
Hi, I just cloned this repo and did a `docker-compose up`, which results in `linux spec capabilities: Unknown capability to add: "CAP_AUDIT_READ"`.

My env:
Centos 7
docker-compose version 1.13.0, build 1719ceb
Docker version 17.06.1-ce, build 874a737

**Comment by jarpy** [comment]
Hi @amosbird,

Unfortunately, Centos 7 doesn't know about `CAP_AUDIT_READ`. It was added in kernel version 3.16, but Centos 7 runs kernel version 3.10.

Without access to the capability, you'll have to run your container in privileged mode to get the same effect.

**Comment by 1kozlovsas** [comment]
Hi, can you provide details on how run the container in privileged mode? I've run "docker-compose up" in privileged mode on CentOS 7, and received the same error. I have to stick with this OS. Is there any other possible workaround?
