### ISSUE TITLE
Cannot startup kibana

### ISSUE THREAD

**Issue by robov** [elastic/stack-docker#20]
In my set I have  a reverse-proxy that points to the docker-sets
When I run your stack, than I cannot connect to my <ip>:5601
When I run the official elk stack compose, then I do have access to the :5601 port,

Any ideas why I cannot connect to your <ip>:5601 port ?
- connection refused-

**Comment by xeraa** [comment]
Just to be sure: You are using the [docker-compose.yml](https://github.com/elastic/stack-docker/blob/master/docker-compose.yml) of this repository and when you run `docker-compose up` on it, you cannot connect to Kibana?

Can you connect to Elasticsearch? And what do you have in your logs?

**Comment by robov** [comment]
Thanks for your reply... I am using the docker compose... I just cannot connect my browser to 5601 to see the kibana start screen
logs of what container are you referring to ?

**Comment by xeraa** [comment]
Logs of your Kibana container: `docker logs <ID of your Kibana container>`

Mine look like this:

```
$ docker logs ec4340b8409a                                                                                                                              01:23:35
{"type":"log","@timestamp":"2017-12-27T00:15:21Z","tags":["status","plugin:kibana@6.1.1","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-12-27T00:15:21Z","tags":["status","plugin:elasticsearch@6.1.1","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
...
```

And a bit later in the log you can see that Kibana is working as expected:

```
...
{"type":"log","@timestamp":"2017-12-27T00:16:05Z","tags":["status","plugin:timelion@6.1.1","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-12-27T00:16:05Z","tags":["listening","info"],"pid":1,"message":"Server running at http://0:5601"}
{"type":"response","@timestamp":"2017-12-27T00:16:06Z","tags":[],"pid":1,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"user-agent":"curl/7.29.0","host":"kibana:5601","accept":"*/*"},"remoteAddress":"172.22.0.8","userAgent":"172.22.0.8"},"res":{"statusCode":302,"responseTime":36,"contentLength":9},"message":"GET / 302 36ms - 9.0B"}
...
```

All the relevant information should be in the first 200 log events or so. Show your log and we can then decide if it's an issue with the docker-compose file or if we should move this discussion to Discuss.

**Comment by robov** [comment]
My logs of the kibana container
I am not sure if it makes a difference if I run behind a reverse proxy..
and I do not know where the ip 172.21.0.2 comes from
The only thing I can observe right now is that I cannot see the kibana dashboard at all when it go to port 5601

```
:["error","elasticsearch","data"],"pid":1,"message":"Request error, retrying\nGET http://elasticsearch:9200/_xpack => connect ECONNREFUSED 17
2.21.0.2:9200"}

```

`{"type":"log","@timestamp":"2017-12-26T09:28:05Z","tags":["status","plugin:kibana@6.1.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"
uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-12-26T09:28:05Z","tags":["status","plugin:elasticsearch@6.1.0","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for
 Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-12-26T09:28:05Z","tags":["error","elasticsearch","admin"],"pid":1,"message":"Request error, retrying\nHEAD http://elasticsearch:9200/ => connect ECONNREFUSED 172.21
.0.2:9200"}
{"type":"log","@timestamp":"2017-12-26T09:28:05Z","tags":["status","plugin:xpack_main@6.1.0","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for El
asticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-12-26T09:28:05Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2017-12-26T09:28:05Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
{"type":"log","@timestamp":"2017-12-26T09:28:05Z","tags":["status","plugin:graph@6.1.0","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elastic
search","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-12-26T09:28:05Z","tags":["status","plugin:xpack_main@6.1.0","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Unable to connect to Elast
icsearch at http://elasticsearch:9200.","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-12-26T09:28:05Z","tags":["status","plugin:graph@6.1.0","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Unable to connect to Elasticsea
rch at http://elasticsearch:9200.","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-12-26T09:28:05Z","tags":["status","plugin:elasticsearch@6.1.0","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Unable to connect to El
asticsearch at http://elasticsearch:9200.","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-12-26T09:28:05Z","tags":["error","elasticsearch","data"],"pid":1,"message":"Request error, retrying\nGET http://elasticsearch:9200/_xpack => connect ECONNREFUSED 17
2.21.0.2:9200"}
{"type":"log","@timestamp":"2017-12-26T09:28:05Z","tags":["status","plugin:monitoring@6.1.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevStat
e":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-12-26T09:28:05Z","tags":["warning","elasticsearch","data"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2017-12-26T09:28:05Z","tags":["warning","elasticsearch","data"],"pid":1,"message":"No living connections"}
{"type":"log","@timestamp":"2017-12-26T09:28:13Z","tags":["reporting","warning"],"pid":1,"message":"Generating a random key for xpack.reporting.encryptionKey. To prevent pending reports from failin
g on restart, please set xpack.reporting.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2017-12-26T09:28:13Z","tags":["status","plugin:reporting@6.1.0","error"],"pid":1,"state":"red","message":"Status changed from uninitialized to red - Unable to connect to
 Elasticsearch at http://elasticsearch:9200.","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-12-26T09:28:13Z","tags":["license","warning","xpack"],"pid":1,"message":"License information from the X-Pack plugin could not be obtained from Elasticsearch for the
 [data] cluster. Error: No Living connections"}
{"type":"log","@timestamp":"2017-12-26T09:28:13Z","tags":["status","plugin:xpack_main@6.1.0","error"],"pid":1,"state":"red","message":"Status changed from red to red - No Living connections","prevS
tate":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
{"type":"log","@timestamp":"2017-12-26T09:28:13Z","tags":["status","plugin:graph@6.1.0","error"],"pid":1,"state":"red","message":"Status changed from red to red - No Living connections","prevState"
:"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
{"type":"log","@timestamp":"2017-12-26T09:28:13Z","tags":["status","plugin:reporting@6.1.0","error"],"pid":1,"state":"red","message":"Status changed from red to red - No Living connections","prevSt
ate":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
{"type":"log","@timestamp":"2017-12-26T09:28:13Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2017-12-26T09:28:13Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
{"type":"log","@timestamp":"2017-12-26T09:28:19Z","tags":["status","plugin:xpack_main@6.1.0","error"],"pid":1,"state":"red","message":"Status changed from red to red - Request Timeout after 3000ms"
,"prevState":"red","prevMsg":"No Living connections"}
{"type":"log","@timestamp":"2017-12-26T09:28:19Z","tags":["status","plugin:graph@6.1.0","error"],"pid":1,"state":"red","message":"Status changed from red to red - Request Timeout after 3000ms","pre
vState":"red","prevMsg":"No Living connections"}
{"type":"log","@timestamp":"2017-12-26T09:28:19Z","tags":["status","plugin:reporting@6.1.0","error"],"pid":1,"state":"red","message":"Status changed from red to red - Request Timeout after 3000ms",
"prevState":"red","prevMsg":"No Living connections"}
{"type":"log","@timestamp":"2017-12-26T09:28:19Z","tags":["status","plugin:elasticsearch@6.1.0","error"],"pid":1,"state":"red","message":"Status changed from red to red - Request Timeout after 3000
ms","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
{"type":"log","@timestamp":"2017-12-26T09:28:21Z","tags":["status","plugin:xpack_main@6.1.0","error"],"pid":1,"state":"red","message":"Status changed from red to red - Red","prevState":"red","prevM
sg":"Request Timeout after 3000ms"}
{"type":"log","@timestamp":"2017-12-26T09:28:21Z","tags":["status","plugin:graph@6.1.0","error"],"pid":1,"state":"red","message":"Status changed from red to red - Red","prevState":"red","prevMsg":"
Request Timeout after 3000ms"}
`

**Comment by xeraa** [comment]
Looks like a regular startup procedure, but it was still in progress. On my machine it took around 50s, but your logs only span around 15s.

Common cause why Kibana might not make it: Not enough memory. Did you increase the size as described at https://github.com/elastic/stack-docker#prerequisites?

Anyway, if the problem persists, please open a discussion on https://discuss.elastic.co/c/kibana and we can debug further there, but this doesn't look like an issue with the code of this repo IMO.

**Comment by robov** [comment]
I am running ubuntu 16... total memory 3.8G
should be enough right ?

**Comment by robov** [comment]
.. span around 15 sec... did I send too little logs ? or did it abort after 15 sec (I cannot understand those logs yet)
