### ISSUE TITLE
Not able to connect to elasticsearch

### ISSUE THREAD

**Issue by jbudz** [elastic/stack-docker#21]
Reported at https://discuss.elastic.co/t/kibana-not-starting-up/113365/5.  I was able to reproduce it, docker-compose up and none of the beats or kibana can reach elasticsearch:9200.

**Comment by xeraa** [comment]
Please provide some logs (and give the setup a few minutes to get properly started). This has been working in general for quite some people already, so we'll need some more details to dive deeper into this.
If you are on Mac or Windows you **must** change your memory settings as [documented in the readme](https://github.com/elastic/stack-docker#prerequisites).

Ref #20

**Comment by robov** [comment]
Awesome... can you please show them your logs... this goes WAAAY beyond my scope of knowledge and experience

**Comment by jbudz** [comment]
@xeraa apologies that did work for me, and thanks for responding on the discuss ticket. 

@robov lets move this back to the discuss ticket, and we can reopen if there's still problems.
