### ISSUE TITLE
.env is not used for ELASTIC_PASSWORD

### ISSUE THREAD

**Issue by vital-st1x** [elastic/stack-docker#25]
Hi,

in case of password changing in .env file all beats (metric, file, audit) could not be registered due lack of permissions.
The reason is that password is not taking from env $ELASTIC_PASSWORD but from configuration files (e.g. /usr/share/filebeat/filebeat.yml for filebeat)

Step to reproduce

1. Clone the repo
2. Change the password in .env file
3. docker-compose up
4. check the status of containers. Example output for filebeat: 

```
Exiting: Couldn't connect to any of the configured Elasticsearch hosts. Errors: [Error connection to Elasticsearch http://elasticsearch:9200: 401 Unauthorized: {"error":{"root_cause":[{"type":"security_exception","reason":"failed to authenticate user [elastic]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"failed to authenticate user [elastic]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}]
```

**Comment by jarpy** [comment]
This a great observation, thanks.

I think the full solution here is to add a complete system of environment-based configuration to the Beats images. Until we have that in place, 5bf93c2e5ab should smooth out the problem in the context of `stack-docker`.

Please let me know if it works for you.

**Comment by vital-st1x** [comment]
@jarpy Thank you so much! It works!
I will close the issue.
