### ISSUE TITLE
Error running elastic stack.

### ISSUE THREAD

**Issue by hsgurm1** [elastic/stack-docker#27]
[root@localhost start]# docker-compose up -d
WARNING: The ELASTIC_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The TAG variable is not set. Defaulting to a blank string.
ERROR: no such image: docker.elastic.co/elasticsearch/elasticsearch-platinum:: invalid reference format

**Comment by xeraa** [comment]
Is it possible that you're missing the [`.env` file](https://github.com/elastic/stack-docker/blob/master/.env)? Because both of those missing environment variables are being set there...

**Comment by hsgurm1** [comment]
Yes i fixed this, but the other issue is not allowing stack to run.
I am running docker-compose up on centos 7. The moment i start the command, my ssh disconnects and ping is not working. I have given 8 GB to VM

**Comment by hsgurm1** [comment]
Thanks was able to fix this. But got error while stack was coming up. 
ERROR: for auditbeat Cannot Start service audit beat : LINUX SPEC CAPABILITIES: UNKNOWN CAPABILITY TO ADD : "CAP_AUDIT_READ"

**Comment by xeraa** [comment]
I assume you're running on Linux with an older kernel. Can you run the following command and check if you get a result similar to the one I get:

```
$ man 7 capabilities | grep CAP_AUDIT_READ
       CAP_AUDIT_READ (since Linux 3.16)
```

You can also check your kernel version (`uname -r`) — you'll probably have a version lower than 3.16.

**Comment by jarpy** [comment]
It's likely you can make it work by setting the `privileged: true` instead. It's less granular, but I think it will work for older kernels.

Please let me know if it works for you!

**Comment by peasead** [comment]
I used `privileged=true` and that seems to have worked around this error on older Kernels.
```
docker run -d --network host --rm --name=auditbeat --user=root -v $(pwd)/auditbeat.docker.yml:/usr/share/auditbeat/auditbeat.yml:z --pid=host --privileged=true docker.elastic.co/beats/auditbeat:7.4.0 -e --strict.perms=false -E output.elasticsearch.hosts=["127.0.0.1:9200"]
```
