### ISSUE TITLE
Canvas for stack-docker

### ISSUE THREAD

**Issue by morgango** [elastic/stack-docker#28]
I would love to see this ...

**Comment by michaelbaamonde** [comment]
Hey, @morgango, thanks for raising this. I chatted with @skearns64 about this, and it seems best to wait until Canvas is on the same release cycle as the rest of the stack to do this. Currently, Canvas's release cadence is very fast, and it's not a packaged with Kibana or X-Pack proper. This doesn't cohere with how the Docker images are built and released, it would introduce difficulties with things like versioning images. We'll have Canvas available via Docker once it's out of the preview phase and integrated with the stack's release process.
