### ISSUE TITLE
Update to 5.X

### ISSUE THREAD

**Issue by morgango** [elastic/stack-docker#3]
This needs to be updated to a modern version (ie not 2.1)

**Comment by michaelbaamonde** [comment]
Assuming you're referring to [this](https://github.com/elastic/stack-docker/blob/master/docker-compose.yml#L2), the `2.1` specifies the version of the docker-compose format, not the Elastic Stack. The latter is controlled by the `ELASTIC_VERSION` environment variable. [Here](https://github.com/elastic/stack-docker/blob/master/docker-compose.yml#L9) is an example invocation. 

The Elastic Docker images are up to date with the upstream products. In fact, we do not even have images for pre-5.0 releases.
