### ISSUE TITLE
"docker-compose up" fails.

### ISSUE THREAD

**Issue by rflorenc** [elastic/stack-docker#4]
### Steps to reproduce

`$ cat /etc/fedora-release`
Fedora release 25 (Twenty Five)`

`$ docker-compose version`
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

`$ docker-compose up`
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.elasticsearch: 'healthcheck'
Unsupported config option for services.kibana: 'healthcheck'
services.filebeat.depends_on contains an invalid type, it should be an array
services.heartbeat.depends_on contains an invalid type, it should be an array
services.kibana.depends_on contains an invalid type, it should be an array
services.logstash.depends_on contains an invalid type, it should be an array
services.metricbeat.depends_on contains an invalid type, it should be an array
services.packetbeat.depends_on contains an invalid type, it should be an array
services.create_logstash_index_pattern.depends_on contains an invalid type, it should be an array
services.import_dashboards.depends_on contains an invalid type, it should be an array
services.set_default_index_pattern.depends_on contains an invalid type, it should be an array

**Comment by xeraa** [comment]
Quoting from the [Docker docs](https://docs.docker.com/engine/reference/builder/#healthcheck):

> The `HEALTHCHECK` feature was added in Docker 1.12.

What's your Docker version? And also the actual *docker-compose.yml* file would help ;-)

**Comment by rflorenc** [comment]
I'm using the docker-compose.yml provided in the repo.

$ sudo docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:18:37 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:18:37 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by rflorenc** [comment]
Definitely some version jinx involved. 
I got it running by taking care of the errors reported by the parser.

**Comment by jarpy** [comment]
Thanks for the nudge here. :)

I just pushed an updated version based on the Compose 3.2 syntax. It's interesting that they dropped support for depending on `service_healthy` as a mechanic for delayed startup. I implemented some alternative health checking with Curl.

https://github.com/elastic/stack-docker/commit/ea389967094a151dba499a044bc773f7ed136d7e
