### ISSUE TITLE
Error response from daemon: No such container: elasticsearch

### ISSUE THREAD

**Issue by MattF-NSIDC** [elastic/stack-docker#50]
I'm just starting to attempt to use this project for the first time from 898d08b and hitting the error in the subject during execution of `setup.sh`. The `docker restart elasticsearch` command is reached before `elasticsearch` container is ever started (following the README) so the `setup_logstash` and `setup_kibana` containers sleep indefinitely waiting for `elasticsearch` container to start.

Here's my logs. I added some output to help me understand what was going on:

```
$ docker-compose -f setup.yml up
<...snip...>
setup_1  | setup_elasticsearch    | Move logstash certs to logstash config dir...
setup_1  | setup_elasticsearch    | Move kibana certs to kibana config dir...
setup_1  | setup_elasticsearch    | Move elasticsearch certs to elasticsearch config dir...
setup_1  | setup_elasticsearch exited with code 0
setup_1  | Restarting elasticsearch...
setup_1  | Error response from daemon: No such container: elasticsearch
setup_1  | RC: 1
setup_1  | Found orphan containers (elasticstack-docker_setup_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
setup_1  | Pulling setup_logstash (docker.elastic.co/logstash/logstash:6.3.0)...
setup_1  | 6.3.0: Pulling from logstash/logstash
setup_1  | Digest: sha256:3f80943ab3bc4ca9ef50eb712cdd720a1e61edeecae5f15388724039e432435a
setup_1  | Status: Downloaded newer image for docker.elastic.co/logstash/logstash:6.3.0
setup_1  | Pulling setup_kibana (docker.elastic.co/kibana/kibana:6.3.0)...
setup_1  | 6.3.0: Pulling from kibana/kibana
setup_1  | Digest: sha256:fd18353e0f980d812e31d52c5c706b614b33dde7728f2be1bb9fc18a531ea364
setup_1  | Status: Downloaded newer image for docker.elastic.co/kibana/kibana:6.3.0
Creating elasticsearch ... done
Creating setup_kibana   ... done
Creating setup_logstash ... done
Attaching to setup_kibana, setup_logstash
setup_1  | setup_kibana           | -rw-rw-r-- 1 root root 1200 Jul 25 01:11 /usr/share/kibana/config/ca/ca.crt
setup_1  | setup_logstash         | -rw-rw-r-- 1 root root 1200 Jul 25 01:11 /usr/share/logstash/config/ca/ca.crt
setup_1  | setup_logstash         | Sleeping while waiting for elasticsearch container...
setup_1  | setup_logstash         | Sleeping while waiting for elasticsearch container...
setup_1  | setup_logstash         | Sleeping while waiting for elasticsearch container...
```

Docker version:
```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false
```

Compose:
```
docker-compose version 1.21.2, build a133471
```

I ended up temporarily dropping back to d52aac2 to get the stack started.

Any help would be greatly appreciated!

**Comment by fxdgear** [comment]
@MattF-NSIDC 

so the `docker restart elasticsearch` instruction in the `setup.sh` isn't needed. It was actually left there on accident and was needed while I was doing some development on this project. 

I've committed the change and shouldn't happen now. 

If you are still seeing a problem with this, please can you give me the results of a `docker ps -a`. I am curious if the Elasticsearch container is failing to start for some reason. It could also be that it's taking some time for the elasticsearch container to actually start. The setup_kibana and setup_logstash actually have to wait until Elasticsearch cluster health is `yellow`. IE able to receive web requests, so there's a startup process that needs to run in the Elasticsearch container. So our setups will sit and wait until the request goes through. 

If it takes longer than say 5-10 seconds, my assumption would be that something is blocking elasticsearch from starting. 

Let me know if there's anything else that I can help with :)

**Comment by MattF-NSIDC** [comment]
@fxdgear Thanks so much for your help! With the most recent commit I'm able to get a stack running on my first fresh attempt.

I attempted to go back to the previous commit to see if I could still reproduce the issue, but I failed. I have no idea what caused it to get stuck so long last time! :man_shrugging: Closing.

Thanks again!
