### ISSUE TITLE
env variable ELASTIC_PASSWORD not honored through ash

### ISSUE THREAD

**Issue by fenchu** [elastic/stack-docker#58]
Hi 

I need to set ELASTIC_PASSWORD and edited ./scripts/setup.sh 
```
if [ -z "${ELASTIC_PASSWORD}" ]; then                                                  
    printf "generating random password since variable ELASTIC_PASSWORD not set\n"      
    PW=$(openssl rand -base64 16;)                                                     
    ELASTIC_PASSWORD="${ELASTIC_PASSWORD:-$PW}"                                        
    export ELASTIC_PASSWORD                                                            
fi                                                                                     
```
but the setup.yml pipe to ash does not seem to honor envionment variables
command: ['cat ./scripts/setup.sh | tr -d "\r" | ash']

it is always undefined.

And before you asked why:
I had a previous setup with lots of logstash, beats, rsyslogs using the old password.
and some of them I do not have access to.

**Comment by fenchu** [comment]
adding
`ELASTIC_PASSWORD=mypassword`
to ~/.env and adding `source ${pwd}/.env` to ./scripts/setup.sh fixed it for me

**Comment by fxdgear** [comment]
@fenchu I'm sorry this was an oversight on my end. 

I've updated the setup.yml to extract the `ELASTIC_PASSWORD` from the host env. 

For example: 

`ELASTIC_PASSWORD=changeme docker-compose -f setup.yml up`
