### ISSUE TITLE
setup-beat.sh: kibana not ready yet but curl gives successfull exit code

### ISSUE THREAD

**Issue by mdiehm** [elastic/stack-docker#66]
Hi,

I tried installing 6.5.1 and encountered the following problem. When setup-beat.sh is run kibana is not ready but returns a string with a message that it's not ready but sends a return code indicating error. We should respect this with the following change and keep waiting.

Worked for me with this fix. 

diff --git a/scripts/setup-beat.sh b/scripts/setup-beat.sh
index 2295d6fe..e5833c4c 100755
--- a/scripts/setup-beat.sh
+++ b/scripts/setup-beat.sh
@@ -4,7 +4,7 @@ set -euo pipefail

 beat=$1

-until curl -s -k http://kibana:5601; do
+until curl -f -s -k http://kibana:5601; do
     echo "Waiting for kibana..."
     sleep 5
 done

**Comment by fxdgear** [comment]
@mdiehm would you be willing to submit a patch??
