### ISSUE TITLE
can't open './scripts/setup.sh': No such file or directory

### ISSUE THREAD

**Issue by SteveDoeve** [elastic/stack-docker#74]
docker-compose -f setup.yml up, does this work on windows?
I did all the steps before as requested.

COMPOSE_CONVERT_WINDOWS_PATHS=1
PWD=/path/to/checkout/for/stack-docke

My path is: /c/Github-repos/stack-docker-master

Doesnt work, when running "docker-compose -f setup.yml up"  I still get "setup_1  | cat: can't open './scripts/setup.sh': No such file or directory"

**Comment by fxdgear** [comment]
@SteveDoeve what version of windows are you using?

**Comment by SteveDoeve** [comment]
Hello,

I am using windows 10 Professional 64-bit.


Op ma 14 jan. 2019 om 19:30 schreef Nick Lang <notifications@github.com>:

**Comment by SteveDoeve** [comment]
I fixed it probably the PWD environment variable was set at system level not at user.

**Comment by nbalu** [comment]
I have the same issue though I'm not sure what can go wrong:

![image](https://user-images.githubusercontent.com/7927881/52541333-fb3c8280-2d93-11e9-9528-9fab438a22f2.png)

The variables seems to be fine, the mounting directory is shared in windows. 

The mound directory is also fine in the docker setup container.

![image](https://user-images.githubusercontent.com/7927881/52541353-3fc81e00-2d94-11e9-82da-849d53477658.png)

And even in the environments the value gets used.

![image](https://user-images.githubusercontent.com/7927881/52541362-5bcbbf80-2d94-11e9-9396-d30c3f749526.png)

Any idea?

Thanks,
Bálint
